### ISSUE TITLE
ImportError: cannot import name 'Robot' from 'controller'

### ISSUE THREAD

**Issue by pmyyyy** [virtualclone/formation_uavs#1]
How should I solve this problem

**Comment by chungshan** [comment]
Hi, how did you install Webots?
You probably missed some steps during installation.
You can check [installation procedure](https://cyberbotics.com/doc/guide/installation-procedure)

**Comment by pmyyyy** [comment]
Thank you for such a prompt reply!
I downloaded it from the address you put on the webpage
But I don't know what steps should I follow to run the whole program
（我看您是台湾同胞，可以中文交流吗）

在2022-02-19 ***@***.***写道：

Hi, how did you install Webots?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chungshan** [comment]
可以的，你的作業系統是Linux或windows?
需要先安裝Webots才能執行這個模擬程式
建議照著步驟安裝，可以參考https://cyberbotics.com/doc/guide/installation-procedure
安裝完Webots 後，可以從Webots直接打開worlds/formation_uavs.wbt 即可

**Comment by pmyyyy** [comment]
謝謝！我的作業系統是windows，我已經安裝好了，接下來應該怎麼運行呢？我第一次使用還不是很了解，謝謝您的解答

在2022-02-19 ***@***.***写道：

可以的，你的作業系統是Linux或windows?
需要先安裝Webots才能執行這個模擬程式
建議照著步驟安裝，可以參考https://cyberbotics.com/doc/guide/installation-procedure

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chungshan** [comment]
安裝完webots後，打開webots，並從webots的工具列File -> Open World 然後選擇此repo的worlds/formation_uavs.wbt 匯入模擬環境，匯入後再按下播放鍵即可開始模擬

**Comment by pmyyyy** [comment]
您好！我已經成功運行，效果很不錯，謝謝您提供的資源！我想請教一下您寫這個仿真的時候是否有參考論文？其中的算法細節是自己推算的嗎？是如何設計的呢？
謝謝您的解答，期待您的回复

在2022-02-21 ***@***.***写道：

安裝完webots後，打開webots，並從webots的工具列File -> Open World 然後選擇此repo的worlds/formation_uavs.wbt 即可

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chungshan** [comment]
控制器的部分是自己推導的，概念類似此篇論文的做法https://www.sciencedirect.com/science/article/pii/S1877705813017384，
另外關於webots模擬器的使用可以參考官網的教學，非常詳細
https://cyberbotics.com/doc/guide/tutorials

**Comment by pmyyyy** [comment]
萬分感謝！謝謝您耐心的解答！如果有什麼問題我能幫助您的，請儘管問我~

在2022-02-21 ***@***.***写道：

控制器的部分是自己推導的，概念類似此篇論文的做法https://www.sciencedirect.com/science/article/pii/S1877705813017384，
另外關於webots模擬器的使用可以參考官網的教學，非常詳細
https://cyberbotics.com/doc/guide/tutorials

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
