### ISSUE TITLE
Can I get some information about this control logic?

### ISSUE THREAD

**Issue by bigbigpark** [virtualclone/formation_uavs#2]
Thanks for sharing your formation uavs in Webots simulator. <br/>
I just started studying the control of UAVs, can you recommend some meterials or related paper about below your code. <br/>

https://github.com/chungshan/formation_uavs/blob/f6ca6f8fd6e4d36cfeb09374147cb80a57853a29/controllers/leader_ctrl/leader_ctrl.py#L119-L137

<br/>

**Comment by chungshan** [comment]
Hi, you can check this out
https://sal.aalto.fi/publications/pdf-files/eluu11_public.pdf

**Comment by bigbigpark** [comment]
Thanks a lot
